### ISSUE TITLE
Segementation fault on NixOS

### ISSUE THREAD

**Issue by nh2** [draios/sysdig#1006]
I'm trying to run sysdig on NixOS, but am getting a crash:

```
[root@machine:~]# sysdig
Segmentation fault

[root@machine:~]# gdb --args sysdig
GNU gdb (GDB) 8.0.1
Reading symbols from sysdig...(no debugging symbols found)...done.
(gdb) r
Starting program: /nix/store/9zrm11d8a0yaab48bdyps819gbwp3li3-system-path/bin/sysdig 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/h1a1ncbkkhapzm0509plqjlfrgxw22f3-glibc-2.25-49/lib/libthread_db.so.1".
warning: File "/nix/store/lai5w1ri6qxkpih86sj543wfwbzl05yw-gcc-6.4.0-lib/lib/libstdc++.so.6.0.22-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
  add-auto-load-safe-path /nix/store/lai5w1ri6qxkpih86sj543wfwbzl05yw-gcc-6.4.0-lib/lib/libstdc++.so.6.0.22-gdb.py
line to your configuration file "/root/.gdbinit".
To completely disable this security protection add
  set auto-load safe-path /
line to your configuration file "/root/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
  info "(gdb)Auto-loading safe path"

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff57aab68 in _int_malloc ()
   from /nix/store/h1a1ncbkkhapzm0509plqjlfrgxw22f3-glibc-2.25-49/lib/libc.so.6
(gdb) bt
#0  0x00007ffff57aab68 in _int_malloc () from /nix/store/h1a1ncbkkhapzm0509plqjlfrgxw22f3-glibc-2.25-49/lib/libc.so.6
#1  0x00007ffff57ac344 in malloc () from /nix/store/h1a1ncbkkhapzm0509plqjlfrgxw22f3-glibc-2.25-49/lib/libc.so.6
#2  0x00007ffff57e44a1 in __alloc_dir () from /nix/store/h1a1ncbkkhapzm0509plqjlfrgxw22f3-glibc-2.25-49/lib/libc.so.6
#3  0x00007ffff57e45a3 in opendir_tail () from /nix/store/h1a1ncbkkhapzm0509plqjlfrgxw22f3-glibc-2.25-49/lib/libc.so.6
#4  0x00000000005de58f in scap_fd_scan_fd_dir ()
#5  0x00000000005d7ef9 in scap_proc_scan_proc_dir ()
#6  0x00000000005ce723 in scap_open_live_int ()
#7  0x0000000000564ddd in sinsp::open(unsigned int) ()
#8  0x00000000005652e5 in sinsp::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#9  0x000000000046b106 in sysdig_init(int, char**) ()
#10 0x000000000044e520 in main ()
(gdb) 
```

Any idea what could be wrong or how I could get more info?

You can see the flags with which sysdig is compiled on NixOS [here](https://github.com/NixOS/nixpkgs/blob/d2dff8d0bea7071f81c59d70db33fdeb47f8199a/pkgs/os-specific/linux/sysdig/default.nix), in case that helps.

**Comment by nh2** [comment]
FWIW, I no longer get segfaults at startup, but still somedimes sporadically when digging (see my update at https://github.com/NixOS/nixpkgs/issues/32485#issuecomment-612729334).

**Comment by nh2** [comment]
Example trace of such segfault:

```
2556999 03:22:29.044472375 0 consul (1728) < futex res=-110(ETIMEDOUT)
2557163 03:22:29.044632583 0 consul (1728) < futex res=-110(ETIMEDOUT)
2557453 03:22:29.044856731 0 consul (1728) < futex res=-110(ETIMEDOUT)
2557743 03:22:29.045081017 0 consul (1728) < futex res=-110(ETIMEDOUT) 
F1Help  F2View AsCTRL+FSearchp Pause BakBack  c Clear CTRL+GGoto       Program received signal SIGSEGV, Segmentation fault.                                                       39/92(97.5%)
                                                                                                                           0x000000000068802a in sinsp_filter_check_event::extract(sinsp_evt*, unsigned int*, bool) ()
(gdb) bt
#0  0x000000000068802a in sinsp_filter_check_event::extract(sinsp_evt*, unsigned int*, bool) ()
#1  0x00000000006605ed in sinsp_filter_check::compare(sinsp_evt*) ()
#2  0x000000000067c13a in sinsp_filter_check_event::compare(sinsp_evt*) ()
#3  0x00000000006606d2 in sinsp_filter_check::compare(gen_event*) ()
#4  0x0000000000694f12 in gen_event_filter_expression::compare(gen_event*) ()
#5  0x0000000000694f12 in gen_event_filter_expression::compare(gen_event*) ()
#6  0x0000000000694f12 in gen_event_filter_expression::compare(gen_event*) ()
#7  0x000000000063d323 in curses_textbox::process_event(sinsp_evt*, int) ()
#8  0x0000000000610a98 in sinsp_cursesui::process_event(sinsp_evt*, int) ()
#9  0x000000000060cf21 in do_inspect(sinsp*, unsigned long, sinsp_cursesui*) ()
#10 0x000000000060e6e1 in csysdig_init(int, char**) ()
#11 0x00000000005fad6f in main ()
```
