### ISSUE TITLE
Segmentation fault anytime (Debian 9) 

### ISSUE THREAD

**Issue by vmessie** [draios/sysdig#1328]
Hello,

I just installed sysdig (latest stable), and I get a segmentation fault each time I try to run it:

    # sysdig
    Erreur de segmentation

Here's my `dmesg`:

```
[200796.816519] sysdig_probe: deallocating consumer ffff8b4c92dbcf00
[200800.251323] sysdig_probe: adding new consumer ffff8b4b4eef2280
[200800.251382] sysdig_probe: initializing ring buffer for CPU 0
[200800.255302] sysdig_probe: CPU buffer initialized, size=8388608
[200800.255303] sysdig_probe: initializing ring buffer for CPU 1
[200800.261781] sysdig_probe: CPU buffer initialized, size=8388608
[200800.419170] sysdig[2086]: segfault at 7faaca2d807e ip 00000000005958b6 sp 00007ffc65033f40 error 4 in sysdig[400000+63e000]
[200800.420008] sysdig_probe: deallocating consumer ffff8b4b4eef2280
```

System informations : 

```
# uname -a
Linux hostname 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```

And when I try to run it on `gdb`
```
(gdb) run
Starting program: /usr/bin/sysdig 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
4 16:46:51.266966103 0 sysdig (31496) > switch next=0 pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0 
5 16:46:51.267191865 0 <NA> (0) > switch next=0 pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0 
6 16:46:51.267195071 0 <NA> (133) > switch next=0 pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0 
7 16:46:51.267402298 1 <NA> (0) > switch next=0 pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0 
Program received signal SIGSEGV, Segmentation fault.
0x00000000004d3830 in sinsp_evt::get_param_as_str(unsigned int, char const**, sinsp_evt::param_fmt) ()
(gdb) bt
#0  0x00000000004d3830 in sinsp_evt::get_param_as_str(unsigned int, char const**, sinsp_evt::param_fmt) ()
#1  0x00000000004f81f7 in sinsp_filter_check_event::extract(sinsp_evt*, unsigned int*, bool) ()
#2  0x00000000004e0156 in sinsp_filter_check::tostring(sinsp_evt*) ()
#3  0x00000000004d7b37 in sinsp_evt_formatter::tostring(sinsp_evt*, std::string*) ()
#4  0x00000000004a8ee4 in do_inspect(sinsp*, unsigned long, unsigned long, bool, bool, bool, bool, sinsp_filter*, std::vector<summary_table_entry, std::allocator<summary_table_entry> >&, sinsp_evt_formatter*) ()
#5  0x00000000004ac701 in sysdig_init(int, char**) ()
#6  0x0000000000497670 in main ()
(gdb)
```

Is it something I did wrong, or an actual issue? 

Thanks in advance for the help !

**Comment by ldegio** [comment]
is there any chance you have manually compiled or recently upgraded sysdig? An error like this one typically happens when the versions of the kernel module and sysdig don't match.

**Comment by vmessie** [comment]
Hello and thank you for your help. Actually, I just installed sysdig (binaries) for the first time, using the repository. But when I compile it from source (and use the kernel module from the git repo), it works perfectly. Thanks!
