### ISSUE TITLE
OSS Sysdig SIGSEGV at startup on sinsp::next(sinsp_evt**)

### ISSUE THREAD

**Issue by lorenzo-david** [draios/sysdig#1527]
I compiled my own sysdig from dev (set to https://github.com/draios/sysdig/commit/35b97c4f0da05713e05b871b3abbf7a71ed54553).

I've been trying to run it on a aws ec2 instance (m5.4xlarge):
```
$ uname -a
Linux ip-172-31-53-95 4.15.0-1052-aws #54-Ubuntu SMP Tue Oct 1 15:43:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Very frequently(about 3 times out of 4), Sysdig immediately crashes.

Here's the relevant stack straces from running gdb:
```
Thread 1 "sysdig" received signal SIGSEGV, Segmentation fault.
0x0000555555ee053a in sinsp::next(sinsp_evt**) ()

(gdb) bt
#0  0x0000555555ee053a in sinsp::next(sinsp_evt**) ()
#1  0x0000555555d51e01 in do_inspect(sinsp*, unsigned long, unsigned long, bool, bool, bool, bool, sinsp_filter*, std::vector<summary_table_entry, std::allocator<summary_table_entry> >&
, sinsp_evt_formatter*) ()
#2  0x0000555555d54eb0 in sysdig_init(int, char**) ()
#3  0x0000555555d2d042 in main ()

(gdb) l
1       in ../sysdeps/x86/dl-procinfo.c

(gdb) disassemble  
   0x0000555555ee04f7 <+55>:    je     0x555555ee0918 <_ZN5sinsp4nextEPP9sinsp_evt+1112>
   0x0000555555ee04fd <+61>:    mov    0x510(%rdi),%rax
   0x0000555555ee0504 <+68>:    movq   $0x0,0x508(%rdi)
   0x0000555555ee050f <+79>:    test   %rax,%rax       
   0x0000555555ee0512 <+82>:    je     0x555555ee051d <_ZN5sinsp4nextEPP9sinsp_evt+93>
   0x0000555555ee0514 <+84>:    mov    0x518(%rdi),%rsi                                
   0x0000555555ee051b <+91>:    callq  *%rax          
   0x0000555555ee051d <+93>:    mov    (%r12),%rax    
   0x0000555555ee0521 <+97>:    lea    -0x1a4d08(%rip),%rdx        # 0x555555d3b820 <_ZN9sinsp_evt6get_tsEv>
   0x0000555555ee0528 <+104>:   mov    0x10(%rax),%rax 
   0x0000555555ee052c <+108>:   cmp    %rdx,%rax
   0x0000555555ee052f <+111>:   jne    0x555555ee0908 <_ZN5sinsp4nextEPP9sinsp_evt+1096>
   0x0000555555ee0535 <+117>:   mov    0x18(%r12),%rax
=> 0x0000555555ee053a <+122>:   mov    (%rax),%r13
   0x0000555555ee053d <+125>:   cmpq   $0x0,0x3c8(%rbx)
   0x0000555555ee0545 <+133>:   jne    0x555555ee055b <_ZN5sinsp4nextEPP9sinsp_evt+155>
   0x0000555555ee0547 <+135>:   mov    0x18(%r12),%rax
   0x0000555555ee054c <+140>:   cmpw   $0x110,0x14(%rax)
   0x0000555555ee0552 <+146>:   je     0x555555ee055b <_ZN5sinsp4nextEPP9sinsp_evt+155>
   0x0000555555ee0554 <+148>:   mov    %r13,0x3c8(%rbx)                                                                                                                                     0x0000555555ee055b <+155>:   cmpb   $0x0,0x548(%rbx)

(gdb) p/x $rax
$1 = 0x0
(gdb) p/x $r13
$2 = 0x0
```

Note that I've compiled it using frame pointers.
```
-       set(CMAKE_COMMON_FLAGS "-Wall -ggdb")
+       set(CMAKE_COMMON_FLAGS "-Wall -ggdb -fno-omit-frame-pointer")
```

**Comment by ldegio** [comment]
most of the times, these kinds of crashes happen when sysdig and the driver have mismatching versions. Is it possible that you are running an older driver?

**Comment by lorenzo-david** [comment]
Just double-checked. I did:
```
$ sudo apt-get autoremove sysdig -y
$ sudo dpkg -i ~/sysdig-0.1.1dev-x86_64.deb 
```
Looks like I'm runinng consistently the right userspace/kmodule.

**Comment by nathan-b** [comment]
Following up: I believe this is https://github.com/draios/sysdig/commit/4f8138feea1f2e0be33df158b22284ec97208cef (PR link: https://github.com/draios/sysdig/pull/1528), fixed in dev. @lorenzo-david, can you confirm that with this fix it doesn't crash?

**Comment by lorenzo-david** [comment]
Yes. I confirm I don't see the crash anymore after https://github.com/draios/sysdig/commit/4f8138feea1f2e0be33df158b22284ec97208cef.
