### ISSUE TITLE
Crash with invalid event name

### ISSUE THREAD

**Issue by gnosek** [draios/sysdig#294]
Just noticed on 0.1.95 (upgraded from 0.1.92 I think):

```
root@ubuntu-amd64:~# sysdig evt.type=not_a_valid_event_name
Segmentation fault (core dumped)
```

Not sure if the backtrace helps (no debug symbols), but I can put the core dump somewhere
```
Core was generated by `sysdig evt.type=not_a_valid_event_name'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007f77b3923178 in std::string::compare(char const*) const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000000000445a94 in sinsp_filter_check_event::parse_filter_value(char const*, unsigned int) ()
#3  0x0000000000443280 in sinsp_filter::parse_check(sinsp_filter_expression*, boolop) ()
#4  0x0000000000443f8f in sinsp_filter::compile(std::string const&) ()
#5  0x00000000004448f4 in sinsp_filter::sinsp_filter(sinsp*, std::string const&, bool) ()
#6  0x0000000000467065 in sinsp::set_filter(std::string const&) ()
#7  0x0000000000427b71 in sysdig_init(int, char**) ()
#8  0x000000000041cba0 in main ()
```

**Comment by ldegio** [comment]
commit 2c7ba77d0a4ebab01fb28aefaac99ff4fac79757 should fix this.
