### ISSUE TITLE
segfault on boot2docker

### ISSUE THREAD

**Issue by davidmnoriega** [draios/sysdig#388]
Forked boot2docker(as of now, its running kernel version 4.0.7) and added bits to build and include the sysdig-probe kernel module in the vm(I'm using docker-machine on a Mac with vmware fusion). I use the container method to launch sysdig, but it segfaults:
```
$ dmesg
[  191.884162] sysdig_probe: adding new consumer ffff880039835010
[  191.884169] sysdig_probe: initializing ring buffer for CPU 0
[  191.888284] sysdig_probe: CPU buffer initialized, size=8388608
[  191.888287] sysdig_probe: starting capture
[  192.674329] sysdig[1908]: segfault at a1 ip 0000000000485733 sp 00007ffea6e4b7b0 error 4 in sysdig[400000+1af000]
[  192.675998] sysdig_probe: deallocating consumer ffff880039835010
[  192.676459] sysdig_probe: no more consumers, stopping capture
```
```
$ gdb sysdig
...
Program received signal SIGSEGV, Segmentation fault.
0x000000000049e33d in scap_get_threadlist_from_driver ()
(gdb) bt
#0  0x000000000049e33d in scap_get_threadlist_from_driver ()
#1  0x0000000000485723 in sinsp::next(sinsp_evt**) ()
#2  0x00000000004338f2 in do_inspect(sinsp*, unsigned long, bool, bool, bool, sinsp_filter*, std::vector<summary_table_entry, std::allocator<summary_table_entry> >*, sinsp_evt_formatter*) ()
#3  0x0000000000436013 in sysdig_init(int, char**) ()
#4  0x00000000004201d0 in main ()
```

**Comment by davidmnoriega** [comment]
nvm, figured out that I need to compile both kernel module and binary for the kernel in question.
