### ISSUE TITLE
Segmentation Fault on NixOS

### ISSUE THREAD

**Issue by markus1189** [draios/sysdig#775]
When running `sysdig` under NixOS, it fails immediately after start with:

```
> sudo sysdig
zsh: segmentation fault  sudo sysdig
```

I created an issue here: nixos/nixpkgs#23404.  

The backtrace via gdb from dumped core:

```
(gdb) backtrace
#0  0x000000000059eabb in scap_proc_get ()
#1  0x000000000053d5ed in sinsp::get_thread(long, bool, bool) ()
#2  0x00000000005370e2 in sinsp_threadinfo::set_cwd(char const*, unsigned int) ()
#3  0x0000000000539dc6 in sinsp_threadinfo::init(scap_threadinfo*) ()
#4  0x000000000053d8e3 in sinsp::on_new_entry_from_proc(void*, long, scap_threadinfo*, scap_fdinfo*, scap*) ()
#5  0x000000000059e259 in scap_proc_scan_proc_dir ()
#6  0x000000000059de68 in scap_proc_scan_proc_dir ()
#7  0x0000000000597954 in scap_open_live_int ()
#8  0x0000000000542a51 in sinsp::open(unsigned int) ()
#9  0x0000000000542e6d in sinsp::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#10 0x000000000046893d in sysdig_init(int, char**) ()
#11 0x0000000000453730 in main ()
```

This happens with both `0.14` and `0.15`, it used to work before `0.14` although I am not quite sure about the concrete version that was the last working one.

Any ideas?  I am happy to provide more infos if required.

**Comment by markus1189** [comment]
Infos about my system:

```
[markus@nixos]$ sysdig --version
sysdig version 0.15.0

[markus@nixos]$ sudo sysdig
Segmentation fault

[markus@nixos]$ cat /proc/version
Linux version 4.9.11 (nixbld@localhost) (gcc version 5.4.0 (GCC) ) #1-NixOS SMP Sat Feb 18 14:11:56 UTC 2017
```

**Comment by markus1189** [comment]
It's working in a newer release of nixos (17.03).
